// import Providers from "./Providers";
import React from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body
                className={clsx(
                    inter.className,
                    'dark:bg-slate-900 bg-slate-200 dark:text-slate-300 text-gray-700'
                )}
            >
                {children}
            </body>
        </html>
    )
}
